# Generated by Django 6.0.1 on 2026-03-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedwebsite',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
